In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
d = pd.read_csv('college_sleep_and_gpa.csv')
d

,student_id,study,university,semester,cohort_code,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,...,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,gpa_change,term_units,term_load_z,under_6h_sleep,sleep_bracket,sleep_midpoint_clock
0,293,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,370.0,6.17,...,0.0500,0.931,4.00,3.76,-0.24,49.0,0.112,0,6-6.5h,07:20
1,294,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,406.8,6.78,...,0.0476,0.862,4.00,3.55,-0.45,49.0,0.112,0,6.5-7h,05:00
2,297,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,253.8,4.23,...,0.1639,0.586,3.00,3.59,0.59,46.0,-0.604,1,<5.5h,05:38
3,303,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,0.0,411.9,6.86,...,0.7854,0.931,3.80,3.46,-0.34,39.0,-2.275,0,6.5-7h,07:52
4,304,1,Carnegie Mellon University,Spring 2018,lac2,Female,0.0,1.0,408.1,6.80,...,0.1538,0.931,3.17,3.50,0.33,39.0,-2.275,0,6.5-7h,04:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,347,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,445.6,7.43,...,0.0950,1.000,3.74,3.74,0.00,46.0,-0.663,0,7-7.5h,04:13
630,349,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,430.8,7.18,...,0.1070,0.276,3.44,3.61,0.17,49.0,-0.139,0,7-7.5h,04:51
631,353,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,360.9,6.01,...,0.0608,1.000,3.62,3.81,0.19,54.0,0.735,0,6-6.5h,06:33
632,356,5,Carnegie Mellon University,Spring 2017,lac1,Male,0.0,0.0,303.8,5.06,...,0.1568,0.276,3.22,1.38,-1.84,48.0,-0.313,1,<5.5h,06:11
633,357,5,Carnegie Mellon University,Spring 2017,lac1,Female,0.0,0.0,397.9,6.63,...,0.2347,0.897,4.00,4.00,0.00,49.0,-0.139,0,6.5-7h,05:48

In [3]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   student_id               634 non-null    int64
 1   study                    634 non-null    int64
 2   university               634 non-null    object
 3   semester                 634 non-null    object
 4   cohort_code              634 non-null    object
 5   gender                   631 non-null    object
 6   first_generation         630 non-null    float64
 7   underrepresented         633 non-null    float64
 8   avg_sleep_minutes        634 non-null    float64
 9   avg_sleep_hours          634 non-null    float64
 10  daytime_sleep_minutes    634 non-null    float64
 11  sleep_midpoint_minutes   634 non-null    float64
 12  bedtime_variability      634 non-null    float64
 13  nights_tracked_fraction  634 non-null    float64
 14  prior_gpa                634 non-null    float64
 15  term_gpa                 634 non-null    float64
 16  gpa_change               634 non-null    float64
 17  term_units               487 non-null    float64
 18  term_load_z              487 non-null    float64
 19  under_6h_sleep           634 non-null    int64
 20  sleep_bracket            634 non-null    object
 21  sleep_midpoint_clock     634 non-null    object
dtypes: float64(13), int64(3), object(6)
memory usage: 109.1+ KB

In [7]:
d.drop(columns = ['student_id','sleep_bracket','sleep_midpoint_clock','cohort_code'],inplace = True)

In [ ]:
#### Observations:

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study                    634 non-null    int64
 1   university               634 non-null    object
 2   semester                 634 non-null    object
 3   gender                   631 non-null    object
 4   first_generation         630 non-null    float64
 5   underrepresented         633 non-null    float64
 6   avg_sleep_minutes        634 non-null    float64
 7   avg_sleep_hours          634 non-null    float64
 8   daytime_sleep_minutes    634 non-null    float64
 9   sleep_midpoint_minutes   634 non-null    float64
 10  bedtime_variability      634 non-null    float64
 11  nights_tracked_fraction  634 non-null    float64
 12  prior_gpa                634 non-null    float64
 13  term_gpa                 634 non-null    float64
 14  gpa_change               634 non-null    float64
 15  term_units               487 non-null    float64
 16  term_load_z              487 non-null    float64
 17  under_6h_sleep           634 non-null    int64
dtypes: float64(13), int64(2), object(3)
memory usage: 89.3+ KB

In [10]:
d.isnull().sum()/len(d) * 100

study                       0.000000
university                  0.000000
semester                    0.000000
gender                      0.473186
first_generation            0.630915
underrepresented            0.157729
avg_sleep_minutes           0.000000
avg_sleep_hours             0.000000
daytime_sleep_minutes       0.000000
sleep_midpoint_minutes      0.000000
bedtime_variability         0.000000
nights_tracked_fraction     0.000000
prior_gpa                   0.000000
term_gpa                    0.000000
gpa_change                  0.000000
term_units                 23.186120
term_load_z                23.186120
under_6h_sleep              0.000000
dtype: float64

In [ ]:
#### Observations:

In [11]:
d.drop(columns = ['term_units','term_load_z'],inplace = True)

In [12]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study                    634 non-null    int64
 1   university               634 non-null    object
 2   semester                 634 non-null    object
 3   gender                   631 non-null    object
 4   first_generation         630 non-null    float64
 5   underrepresented         633 non-null    float64
 6   avg_sleep_minutes        634 non-null    float64
 7   avg_sleep_hours          634 non-null    float64
 8   daytime_sleep_minutes    634 non-null    float64
 9   sleep_midpoint_minutes   634 non-null    float64
 10  bedtime_variability      634 non-null    float64
 11  nights_tracked_fraction  634 non-null    float64
 12  prior_gpa                634 non-null    float64
 13  term_gpa                 634 non-null    float64
 14  gpa_change               634 non-null    float64
 15  under_6h_sleep           634 non-null    int64
dtypes: float64(11), int64(2), object(3)
memory usage: 79.4+ KB

In [13]:
d.isnull().sum()

study                      0
university                 0
semester                   0
gender                     3
first_generation           4
underrepresented           1
avg_sleep_minutes          0
avg_sleep_hours            0
daytime_sleep_minutes      0
sleep_midpoint_minutes     0
bedtime_variability        0
nights_tracked_fraction    0
prior_gpa                  0
term_gpa                   0
gpa_change                 0
under_6h_sleep             0
dtype: int64

In [16]:
d = d.dropna()

In [17]:
d.isnull().sum()

study                      0
university                 0
semester                   0
gender                     0
first_generation           0
underrepresented           0
avg_sleep_minutes          0
avg_sleep_hours            0
daytime_sleep_minutes      0
sleep_midpoint_minutes     0
bedtime_variability        0
nights_tracked_fraction    0
prior_gpa                  0
term_gpa                   0
gpa_change                 0
under_6h_sleep             0
dtype: int64

In [18]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 626 entries, 0 to 633
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study                    626 non-null    int64
 1   university               626 non-null    object
 2   semester                 626 non-null    object
 3   gender                   626 non-null    object
 4   first_generation         626 non-null    float64
 5   underrepresented         626 non-null    float64
 6   avg_sleep_minutes        626 non-null    float64
 7   avg_sleep_hours          626 non-null    float64
 8   daytime_sleep_minutes    626 non-null    float64
 9   sleep_midpoint_minutes   626 non-null    float64
 10  bedtime_variability      626 non-null    float64
 11  nights_tracked_fraction  626 non-null    float64
 12  prior_gpa                626 non-null    float64
 13  term_gpa                 626 non-null    float64
 14  gpa_change               626 non-null    float64
 15  under_6h_sleep           626 non-null    int64
dtypes: float64(11), int64(2), object(3)
memory usage: 83.1+ KB

In [19]:
y = d['gpa_change']
X = d.drop(columns = 'gpa_change')

In [20]:
print(y.shape)
print(X.shape)

(626,)
(626, 15)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(500, 15)
(126, 15)
(500,)
(126,)

In [24]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 477 to 103
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   study                    500 non-null    int64
 1   university               500 non-null    object
 2   semester                 500 non-null    object
 3   gender                   500 non-null    object
 4   first_generation         500 non-null    float64
 5   underrepresented         500 non-null    float64
 6   avg_sleep_minutes        500 non-null    float64
 7   avg_sleep_hours          500 non-null    float64
 8   daytime_sleep_minutes    500 non-null    float64
 9   sleep_midpoint_minutes   500 non-null    float64
 10  bedtime_variability      500 non-null    float64
 11  nights_tracked_fraction  500 non-null    float64
 12  prior_gpa                500 non-null    float64
 13  term_gpa                 500 non-null    float64
 14  under_6h_sleep           500 non-null    int64
dtypes: float64(10), int64(2), object(3)
memory usage: 62.5+ KB

In [26]:
from sklearn.preprocessing import OrdinalEncoder,MinMaxScaler
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers = [('t1',OrdinalEncoder(),[1,2,3]),
                                               ('t2',MinMaxScaler(),[0,4,5,6,7,8,9,10,11,12,13,14])],
                                remainder = 'passthrough')
X_train_trans = transformer.fit_transform(X_train)
X_test_trans = transformer.transform(X_test)

In [27]:
X_train_trans = pd.DataFrame(X_train_trans,columns = X_train.columns)
X_train_trans.head()

,study,university,semester,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,daytime_sleep_minutes,sleep_midpoint_minutes,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,under_6h_sleep
0,1.0,0.0,1.0,0.75,0.0,0.0,0.456390,0.455696,0.062414,0.287898,0.006801,0.787532,0.908642,0.945205,0.0
1,0.0,2.0,1.0,0.00,0.0,0.0,0.382609,0.382911,0.138621,0.513819,0.047965,0.693384,0.753086,0.863014,1.0
2,2.0,2.0,0.0,0.25,0.5,1.0,0.723847,0.723101,0.100000,0.474874,0.030370,0.818066,0.640329,0.651781,0.0
3,2.0,2.0,1.0,0.25,0.0,0.0,0.642951,0.642405,0.139310,0.258585,0.004256,0.818066,0.670782,0.736438,0.0
4,1.0,0.0,1.0,0.75,0.0,0.0,0.655863,0.656646,0.181379,0.191583,0.003111,1.000000,1.000000,1.000000,0.0

In [28]:
X_test_trans = pd.DataFrame(X_test_trans,columns = X_test.columns)
X_test_trans.head()

,study,university,semester,gender,first_generation,underrepresented,avg_sleep_minutes,avg_sleep_hours,daytime_sleep_minutes,sleep_midpoint_minutes,bedtime_variability,nights_tracked_fraction,prior_gpa,term_gpa,under_6h_sleep
0,1.0,0.0,1.0,0.75,0.0,0.0,0.479842,0.479430,0.107241,0.246231,0.014539,0.872774,0.862963,0.878356,0.0
1,1.0,0.0,1.0,0.75,0.0,0.0,0.434783,0.435127,0.407241,0.168132,0.020141,0.958015,0.917695,0.908767,0.0
2,2.0,3.0,0.0,0.50,0.0,0.0,0.597628,0.598101,0.093103,0.227387,0.002824,1.000000,0.944444,0.964384,0.0
3,2.0,2.0,1.0,0.25,0.5,0.0,0.645323,0.645570,0.095172,0.069095,0.006701,1.000000,0.839095,0.926301,0.0
4,1.0,0.0,1.0,0.75,0.5,0.0,0.349671,0.349684,0.128966,0.240997,0.012133,0.872774,0.862963,0.947945,1.0

In [30]:
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor()
knn_model.fit(X_train_trans,y_train)

KNeighborsRegressor()

In [31]:
y_pred = knn_model.predict(X_test_trans)

In [32]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.06155637425861615